# Generated by Django 5.2 on 2025-04-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_customuser_role_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('STUDENT', 'Student Report'), ('TEACHER', 'Teacher Report'), ('GROUP', 'Group Report'), ('CENTER', 'Center Report')], max_length=10)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom Range')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('attended_sessions', models.IntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_sessions', models.IntegerField(default=0)),
                ('excused_absences', models.IntegerField(default=0)),
                ('unexcused_absences', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_attendance_reports', to='accounts.center')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_attendance_reports', to='accounts.traininggroup')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_reports', to='accounts.userprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_reports', to='accounts.userprofile')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_attendance_reports', to='accounts.training')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'start_date', 'end_date'], name='reports_att_report__f507a3_idx'), models.Index(fields=['student', 'start_date'], name='reports_att_student_04fa1d_idx'), models.Index(fields=['teacher', 'start_date'], name='reports_att_teacher_71edcf_idx'), models.Index(fields=['group', 'start_date'], name='reports_att_group_i_d15234_idx'), models.Index(fields=['center', 'start_date'], name='reports_att_center__1285f5_idx')],
            },
        ),
    ]
