# Generated by Django 5.2 on 2025-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_city_training_association_center_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('association_staff', 'Association_staff'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
    ]
