# Generated by Django 5.2 on 2025-04-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('association_staff', 'Association_staff'), ('teacher', 'Teacher'), ('student', 'Student'), ('center_staff', 'Center_staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('association', 'Association'), ('teacher', 'Teacher'), ('student', 'Student'), ('center_staff', 'Center_staff')], max_length=20, null=True),
        ),
    ]
