# Generated by Django 5.2 on 2025-04-14 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.traininggroup')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_slots', to='accounts.userprofile')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.training')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'day_of_week', 'start_time'), name='unique_teacher_timeslot'), models.UniqueConstraint(fields=('room', 'day_of_week', 'start_time'), name='unique_room_timeslot'), models.UniqueConstraint(fields=('group', 'day_of_week', 'start_time'), name='unique_group_timeslot')],
            },
        ),
    ]
